# coding: utf-8

"""
    Mergin

    This is a simple Mergin src.  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import py-mergin-client
from py-mergin-client.models.storage_params import StorageParams  # noqa: E501
from py-mergin-client.rest import ApiException


class TestStorageParams(unittest.TestCase):
    """StorageParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStorageParams(self):
        """Test StorageParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = py-mergin-client.models.storage_params.StorageParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
