# coding: utf-8

"""
    Mergin

    This is a simple Mergin src.  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import py-mergin-client
from py-mergin-client.api.project_api import ProjectApi  # noqa: E501
from py-mergin-client.rest import ApiException


class TestProjectApi(unittest.TestCase):
    """ProjectApi unit test stubs"""

    def setUp(self):
        self.api = py-mergin-client.api.project_api.ProjectApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_project(self):
        """Test case for add_project

        Add a new mergin project.  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete a project.  # noqa: E501
        """
        pass

    def test_download_project(self):
        """Test case for download_project

        Download dir for single project.  # noqa: E501
        """
        pass

    def test_download_project_file(self):
        """Test case for download_project_file

        Download single project file.  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Find project by name.  # noqa: E501
        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        Find all mergin projects.  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Update an existing project.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
