# coding: utf-8

"""
    Mergin

    This is a simple Mergin src.  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FileInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path': 'str',
        'type': 'str',
        'mtime': 'str',
        'size': 'int'
    }

    attribute_map = {
        'path': 'path',
        'type': 'type',
        'mtime': 'mtime',
        'size': 'size'
    }

    def __init__(self, path=None, type=None, mtime=None, size=None):  # noqa: E501
        """FileInfo - a model defined in Swagger"""  # noqa: E501

        self._path = None
        self._type = None
        self._mtime = None
        self._size = None
        self.discriminator = None

        if path is not None:
            self.path = path
        if type is not None:
            self.type = type
        if mtime is not None:
            self.mtime = mtime
        if size is not None:
            self.size = size

    @property
    def path(self):
        """Gets the path of this FileInfo.  # noqa: E501


        :return: The path of this FileInfo.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this FileInfo.


        :param path: The path of this FileInfo.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def type(self):
        """Gets the type of this FileInfo.  # noqa: E501


        :return: The type of this FileInfo.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FileInfo.


        :param type: The type of this FileInfo.  # noqa: E501
        :type: str
        """
        allowed_values = ["folder", "file"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def mtime(self):
        """Gets the mtime of this FileInfo.  # noqa: E501


        :return: The mtime of this FileInfo.  # noqa: E501
        :rtype: str
        """
        return self._mtime

    @mtime.setter
    def mtime(self, mtime):
        """Sets the mtime of this FileInfo.


        :param mtime: The mtime of this FileInfo.  # noqa: E501
        :type: str
        """

        self._mtime = mtime

    @property
    def size(self):
        """Gets the size of this FileInfo.  # noqa: E501


        :return: The size of this FileInfo.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this FileInfo.


        :param size: The size of this FileInfo.  # noqa: E501
        :type: int
        """

        self._size = size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
