# coding: utf-8

"""
    Mergin

    This is a simple Mergin src.  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ProjectMeta(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'size': 'int',
        'files_count': 'int'
    }

    attribute_map = {
        'size': 'size',
        'files_count': 'files_count'
    }

    def __init__(self, size=None, files_count=None):  # noqa: E501
        """ProjectMeta - a model defined in Swagger"""  # noqa: E501

        self._size = None
        self._files_count = None
        self.discriminator = None

        if size is not None:
            self.size = size
        if files_count is not None:
            self.files_count = files_count

    @property
    def size(self):
        """Gets the size of this ProjectMeta.  # noqa: E501


        :return: The size of this ProjectMeta.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this ProjectMeta.


        :param size: The size of this ProjectMeta.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def files_count(self):
        """Gets the files_count of this ProjectMeta.  # noqa: E501


        :return: The files_count of this ProjectMeta.  # noqa: E501
        :rtype: int
        """
        return self._files_count

    @files_count.setter
    def files_count(self, files_count):
        """Sets the files_count of this ProjectMeta.


        :param files_count: The files_count of this ProjectMeta.  # noqa: E501
        :type: int
        """

        self._files_count = files_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectMeta):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
